### ISSUE TITLE
Single source of truth of supported operators

### ISSUE THREAD

**Issue by guilhermedeoliveira** [TallerWebSolutions/dojo-tdd#1]
To avoid `two sources of truth` for supported operators and to avoid modifying several code lines in test suite that rely on the export of `supportedOperators` variable. I thought about the following solution in `calculator.js`:

remove line
```sh
const supportedOperators = ['+', '-', '*', '/', '^']
```

keep as `source of truth` the object `funcOperators` and move it to before `getOperatorFunc`

```sh
const funcOperators = {
    '+': sum,
    '-': subtract,
    '*': multiply,
    '/': divide,
    '^': exponential,
  }
```

modify `line 20` to
```sh
if (!Object.keys(funcOperators).includes(operator)) {
```

and export at the end
```sh
module.exports = {
  sum,
  exec,
  divide,
  subtract,
  multiply,
  getOperatorFunc,
  extractOperator,
  exponential,
  extractTokens,
  supportedOperators: Object.keys(funcOperators),
}
```

**Comment by sebas5384** [comment]
done!
